#!/bin/bash
set -euxo pipefail

[[ -f './localhost.pem' && -f './localhost-key.pem' ]] || (
  echo '{
    "key": {
      "algo": "rsa",
      "size": 2048
    }
  }' |
    cfssl selfsign 'localhost' - |
    cfssljson -bare 'localhost'
)

deno run --allow-net --allow-read \
  'https://deno.land/std@0.66.0/http/file_server.ts' './stadia.run/' \
  --port 57404 --cors \
   --host 'localhost' --cert './localhost.pem' --key './localhost-key.pem'
